### ISSUE TITLE
Message tests

### ISSUE THREAD

**Issue by dkrasner** [UnitedLexCorp/SimpleTalk#50]
At the moment we have 

1. grammar tests which verify parsing (see issue #49 for how this could be improved)
2. compiler tests which verify that scripts compile to their corresponding messages
3. various system level method tests (adding parts, navigation etc)

We don't have a consistent way to tie 2 & 3 above, i.e. we need tests that will verify that specific messages will actually cause expected changes to the system state.

**Comment by darth-cheney** [comment]
This is now taken care of by two things:
1. There is no need for "compiler" tests, because we have switched to use the semantic-based interpreter scheme, which is itself tested by:
2. Integration tests that we have made (using preload, for example) that require a System and check the state.
  
I am closing for now.
